[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"

[dependencies]
num-integer = "0.1.45"
z3 = "0.12.1"
